name = "four-sense"
main = ".open-next/worker.js"
account_id = "544971d734e2d2605d77624f56f6e72d"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat","global_fetch_strictly_public"]

[assets]
binding = "ASSETS"
directory = ".open-next/assets"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "four-sense-new-db"
database_id = "1ac8c424-7722-4894-92e6-6473bf090abc"
migrations_dir = "drizzle"

# Preview environment
[env.preview]
name = "four-sense-preview"
vars = { ENVIRONMENT = "preview" }

[[env.preview.d1_databases]]
binding = "DB"
database_name = "four-sense-new-db"
database_id = "1ac8c424-7722-4894-92e6-6473bf090abc"
migrations_dir = "drizzle"
